export const homeActions = {
  GET_DEVICE_DETAIL: 'GET_DEVICE_DETAIL',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_MACHINE_ID: 'GET_MACHINE_ID',
  GET_USER_FROM_SESSION: 'GET_USER_FROM_SESSION',
  MARK_DANGEROUS: 'MARK_DANGEROUS',
  CREATE_SNAPSHOT: 'CREATE_SNAPSHOT',
  GET_NEW_IMAGE: 'GET_NEW_IMAGE',
  FETCH_IMAGE_DETAIL: 'FETCH_IMAGE_DETAIL',
};
